"""Tier 1 — Corpus Regression: every owner-verified document must reproduce
its exact BOQ, every run, forever.

This is the "eternal guarantee" the project commits to: once a document's
verdict is captured in ``tests/regression/expectations.json`` and committed
to git, the pipeline's output for that exact document must never silently
change or regress. If a future change drops a row, adds a row, or shifts a
captured count, this test fails immediately — at the exact doc_id — so the
regression is caught at PR time, not in production.

LOCK PROTOCOL (per task P5_02 §3 / §4 / §7):
- Expectations are generated by ``scripts/gen_regression_expectations.py``
  reading the accepted ``results/fidelity/summary.json`` + the
  ``data/real_rfqs/source_truth.json`` ruler. The script is the ONLY
  sanctioned way to write ``tests/regression/expectations.json``; hand-edits
  fail ``--check`` and produce a non-zero exit so a CI gate can catch them.
- The six sacred-10 PASS docs are the authoritative lock set
  (01_gsecl_wanakbori_tmd8, 02_isro_vssc, 03_zydus_matoda_osd,
  05_zydus_animal_pharmez, 09_gem_bid_7439924, 10_gem_bid_7552777).
  01_gsecl moved to PASS after the source-truth correction in task 1.
- The four sacred-10 FAIL docs (04, 06, 07, 08) are listed as
  out-of-scope-until-fixed in expectations.json — visible, with a reason,
  but NOT asserted. Each has an owner-ruling or source-truth-correction
  pending per ``04_LEDGER.md`` and ``SOURCE_TRUTH_REVIEW_06_07_08.md``.
- All other PASS-verdict docs in the accepted summary are locked exact
  alongside the sacred-10. They are marked scope="non-sacred-pass" or
  "trivially-pass" for visibility, and their exact captured counts are
  asserted. Per P5_02 §6, no PASS-verdict doc is silently omitted.
- ``tests/regression/`` is FROZEN per the anti-cheat protocol Rule 5; this
  file is one of the sanctioned frozen-file tasks (P5_02), and the
  orchestrator re-pins expectations.json itself after the agent's diff is
  reviewed. Nothing else in the frozen set moves.

This test ASSERTS REAL EXACT COUNTS, not ranges. Per task §7: "No assertion
may be weaker than the accepted fidelity state (exact counts, not ranges)."
"""

from __future__ import annotations

import json
import sys
import time
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
EXPECTATIONS_PATH = REPO_ROOT / "tests" / "regression" / "expectations.json"
SOURCE_TRUTH_PATH = REPO_ROOT / "data" / "real_rfqs" / "source_truth.json"
SUMMARY_PATH = REPO_ROOT / "results" / "fidelity" / "summary.json"

REPO_ROOT_STR = str(REPO_ROOT)
if REPO_ROOT_STR not in sys.path:
    sys.path.insert(0, REPO_ROOT_STR)


def _load_expectations() -> dict:
    if not EXPECTATIONS_PATH.exists():
        pytest.fail(
            f"expectations.json missing at {EXPECTATIONS_PATH}. "
            "Run `python3 scripts/gen_regression_expectations.py --write` "
            "and commit it. This file is the project lock per task P5_02."
        )
    return json.loads(EXPECTATIONS_PATH.read_text())


def _run_pipeline_for_doc(source_path: str, fmt: str) -> list:
    """Run the appropriate pipeline path for a single doc, returning BoqRow list.

    Mirrors the rule in scripts/audit_fidelity_per_doc.py: PDF goes through
    Pipeline().run() (which returns an ExtractionResult); XLSX goes through
    XLSXRowPipeline().run() (which returns a flat list of BoqRow).
    """
    p = REPO_ROOT / source_path
    if not p.exists():
        pytest.fail(f"Source file missing: {p} (locked expectation cannot run)")
    if fmt == "xlsx":
        from src.pipeline_xlsx import XLSXRowPipeline

        return XLSXRowPipeline().run(str(p))
    from src.pipeline import Pipeline

    result = Pipeline().run(str(p))
    return list(getattr(result, "boq_items", []) or [])


def _detect_format_from_path(source_path: str) -> str:
    """xlsx/xls -> 'xlsx'; everything else -> 'pdf' (covers .pdf, .docx, etc)."""
    s = source_path.lower()
    if s.endswith(".xlsx") or s.endswith(".xls"):
        return "xlsx"
    return "pdf"


def test_expectations_file_present_and_well_formed() -> None:
    """Sanity gate: the expectations file exists, parses, and has the locked
    structure. This is the cheap health check; the per-doc tests below are
    the real assertions."""
    expectations = _load_expectations()
    assert expectations.get("schema_version") == "1.0.0"
    assert "pass_docs" in expectations and "excluded_docs" in expectations
    assert expectations["pass_doc_count"] == len(expectations["pass_docs"])
    assert expectations["excluded_doc_count"] == len(expectations["excluded_docs"])


def test_6_sacred_pass_docs_are_locked() -> None:
    """The 6 sacred-10 PASS docs are the authoritative lock set. If any are
    missing from expectations with sacred10_baseline_pass=True, the lock is
    wrong — catch it at CI time, not at handoff time.
    """
    expectations = _load_expectations()
    sacred_ids = {
        "01_gsecl_wanakbori_tmd8",
        "02_isro_vssc",
        "03_zydus_matoda_osd",
        "05_zydus_animal_pharmez",
        "09_gem_bid_7439924",
        "10_gem_bid_7552777",
    }
    locked_ids = {d["doc_id"] for d in expectations["pass_docs"] if d.get("sacred10_baseline_pass")}
    missing = sacred_ids - locked_ids
    assert not missing, f"sacred PASS docs missing from expectations lock: {missing}"


def test_4_sacred_fail_docs_are_excluded_with_reason() -> None:
    """The 4 sacred-10 FAIL docs must be in expectations with scope=
    'out-of-scope-until-fixed' AND a non-empty reason. Per task gotcha:
    "EXCLUDED with the reason string — visible, not forgotten".
    """
    expectations = _load_expectations()
    sacred_fail_ids = {
        "04_adani",
        "06_avante_kirloskar_pune",
        "07_grew_solar_narmadapuram",
        "08_sael",
    }
    by_id = {d["doc_id"]: d for d in expectations["excluded_docs"]}
    for did in sacred_fail_ids:
        assert did in by_id, f"sacred FAIL doc {did} missing from excluded_docs"
        entry = by_id[did]
        assert entry.get("scope") == "out-of-scope-until-fixed", (
            f"{did} should have scope=out-of-scope-until-fixed, got {entry.get('scope')}"
        )
        assert entry.get("reason"), f"{did} has empty reason — must be visible, not forgotten"
        assert entry.get("sacred10_baseline_fail") is True


def _pdf_pass_indexes() -> set[int]:
    expectations = _load_expectations()
    return {
        i
        for i, d in enumerate(expectations["pass_docs"])
        if not str(d["source_path"]).lower().endswith((".xlsx", ".xls"))
    }


@pytest.mark.parametrize(
    "expectation_doc_index",
    [
        pytest.param(i, marks=pytest.mark.slow if i in _pdf_pass_indexes() else [])
        for i in range(11)
    ],
    ids=lambda i: f"pass_idx_{i}",
)
def test_pass_doc_pipeline_reproduces_locked_counts(expectation_doc_index: int) -> None:
    """For each doc in expectations.pass_docs: run the pipeline, count
    captured, and assert it equals the locked value EXACTLY. Per task §7
    the assertion must be exact, not a range.

    PDF pass docs are marked slow so ``make test`` keeps its default tier
    fast; ``make regression`` runs them all.
    """
    expectations = _load_expectations()
    pass_docs = expectations["pass_docs"]
    if expectation_doc_index >= len(pass_docs):
        pytest.skip(
            f"expectation_doc_index {expectation_doc_index} >= {len(pass_docs)} pass docs"
        )
    doc = pass_docs[expectation_doc_index]
    doc_id = doc["doc_id"]
    expected_captured = int(doc["captured_count"])
    expected_flagged = int(doc["flagged_count"])
    expected_source_rows = int(doc["source_row_count"])
    source_path = doc["source_path"]

    fmt = _detect_format_from_path(source_path)
    if doc.get("scope") == "trivially-pass":
        # 0/0 spec-only doc — guard against invention. The full pipeline run
        # is part of the assertion (must produce exactly 0 captured rows).
        pass

    t0 = time.time()
    try:
        boq = _run_pipeline_for_doc(source_path, fmt)
    except Exception as exc:
        pytest.fail(f"Pipeline error on locked doc {doc_id} ({source_path}): {exc!r}")
    elapsed = time.time() - t0
    actual_captured = len(boq)
    actual_flagged = sum(
        1 for r in boq
        if float(getattr(r, "confidence", 1.0)) < 0.70 or getattr(r, "warnings", None)
    )

    # The capture count is the load-bearing assertion: it must match the
    # locked value EXACTLY. Any drift = regression = fail loudly.
    assert actual_captured == expected_captured, (
        f"FIDELITY REGRESSION on {doc_id}: pipeline produced {actual_captured} rows "
        f"but expectations lock it at {expected_captured} (source={expected_source_rows}, "
        f"flagged_actual={actual_flagged} flagged_locked={expected_flagged}, "
        f"elapsed={elapsed:.1f}s, source={source_path})"
    )
    # Flagged count is also locked; it changes only when the pipeline adds/
    # removes a low-confidence flag, which is also a fidelity signal.
    assert actual_flagged == expected_flagged, (
        f"FLAGGED-COUNT DRIFT on {doc_id}: actual={actual_flagged} expected={expected_flagged} "
        f"(elapsed={elapsed:.1f}s). Flags are a fidelity signal — drift means "
        f"the pipeline is now flagging (or not flagging) different rows."
    )


@pytest.mark.slow
def test_all_pass_docs_match_expectations() -> None:
    """Aggregate sanity: a single doc-by-doc pass over pass_docs that prints
    a verdict table. Marked slow so the default tier skips it; `make
    regression` runs it. This is the "eternal guarantee" assertion: every
    locked doc must reproduce."""
    expectations = _load_expectations()
    pass_docs = expectations["pass_docs"]
    print(f"\n--- Tier 1 regression: asserting {len(pass_docs)} pass docs ---")
    for doc in pass_docs:
        doc_id = doc["doc_id"]
        expected_captured = int(doc["captured_count"])
        source_path = doc["source_path"]
        fmt = _detect_format_from_path(source_path)
        t0 = time.time()
        boq = _run_pipeline_for_doc(source_path, fmt)
        elapsed = time.time() - t0
        actual = len(boq)
        ok = "OK" if actual == expected_captured else "FAIL"
        print(
            f"  [{ok}] {doc_id:<35} expected={expected_captured:>3} actual={actual:>3} "
            f"elapsed={elapsed:5.1f}s  ({source_path})"
        )
        assert actual == expected_captured, (
            f"regression on {doc_id}: expected {expected_captured} captured, got {actual}"
        )
